name = "fluxmind"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "fluxmind"

# Conta específica para este projeto
[env.production.vars]
CLOUDFLARE_ACCOUNT_ID = "d43d1b01c63fde30fdf2fb8a35f57c25"